# generated by Neptune Namespaces v3.x.x
# file: Art.Nano.Engine/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Nano.Engine', class Engine extends Neptune.PackageNamespace
  @version: require('../../package.json').version
