# generated by Neptune Namespaces v3.x.x
# file: Art.Nano.Canvas/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Canvas'
.addModules
  CompositeModes: require './CompositeModes'
  DasmAssembler:  require './DasmAssembler' 
  DasmOpcodes:    require './DasmOpcodes'   
  DasmRuntime:    require './DasmRuntime'   
  NanoBitmap:     require './NanoBitmap'    
  Paths:          require './Paths'         
  StandardImport: require './StandardImport'
  Tools:          require './Tools'         