# generated by Neptune Namespaces v3.x.x
# file: Art.Nano.Canvas/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DasmOpcodes:    require './DasmOpcodes'   
  DasmRuntime:    require './DasmRuntime'   
  NanoBitmap:     require './NanoBitmap'    
  StandardImport: require './StandardImport'
  Tools:          require './Tools'         