# generated by Neptune Namespaces v3.x.x
# file: Art.Nano.Canvas/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CompositeModes:  require './CompositeModes' 
  DasmAssembler:   require './DasmAssembler'  
  DasmOpcodes:     require './DasmOpcodes'    
  DasmRuntime:     require './DasmRuntime'    
  NanoBitmap:      require './NanoBitmap'     
  NanoDrawContext: require './NanoDrawContext'
  Paths:           require './Paths'          
  StandardImport:  require './StandardImport' 
  Tools:           require './Tools'          