# generated by Neptune Namespaces v3.x.x
# file: Art.Nano.Canvas/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Nano.Canvas', class Canvas extends Neptune.PackageNamespace
  @version: require('../../package.json').version
