# generated by Neptune Namespaces v3.x.x
# file: Art.Nano.Atomics/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Atomics'
.addModules
  NanoAtomicBase: require './NanoAtomicBase'
  NanoMatrix:     require './NanoMatrix'    
  NanoPoint:      require './NanoPoint'     
  NanoRectangle:  require './NanoRectangle' 