# generated by Neptune Namespaces v3.x.x
# file: Art.Nano.Atomics/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Nano.Atomics', class Atomics extends Neptune.PackageNamespace
  @version: require('../../package.json').version
