# generated by Neptune Namespaces v3.x.x
# file: perfs/Art.Nano.Engine/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Element:            require './Element'           
  TestElementFactory: require './TestElementFactory'