# generated by Neptune Namespaces v3.x.x
# file: perfs/Art.Nano.Engine/namespace.coffee

module.exports = (require '../namespace').addNamespace('Art.Nano.Engine', class Engine extends Neptune.PackageNamespace)
