# generated by Neptune Namespaces v3.x.x
# file: perfs/Art/Nano/BrowserBaseline/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ArrayBuffer:          require './ArrayBuffer'         
  ConstNamedOpCodes:    require './ConstNamedOpCodes'   
  CreateParallelDataVm: require './createParallelDataVm'
  InlineObjects:        require './InlineObjects'       