# generated by Neptune Namespaces v3.x.x
# file: perfs/Art/Nano/BrowserBaseline/namespace.coffee

module.exports = (require '../namespace').addNamespace('BrowserBaseline', class BrowserBaseline extends Neptune.PackageNamespace)
