# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Nano/Atomics/namespace.coffee

module.exports = (require '../namespace').addNamespace('Atomics', class Atomics extends Neptune.PackageNamespace)
