# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Nano/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Nano', class Nano extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
require './Atomics/namespace';
require './Canvas/namespace';
require './Engine/namespace'