# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Nano.Engine/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Nano.Engine', class Engine extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
