# generated by Neptune Namespaces v3.x.x
# file: perfs/Art/Nano/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Nano', class Nano extends Neptune.PackageNamespace
  @version: require('../../../../package.json').version
require './Atomics/namespace';
require './BrowserBaseline/namespace'